name: Extract Apple Developer Credentials

on:
  workflow_dispatch:
    inputs:
      bundle_id:
        description: 'Your App Bundle Identifier (e.g., com.example.myapp)'
        required: true
        default: 'com.yourcompany.yourapp'

jobs:
  extract-credentials:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Xcode
      run: |
        sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer
        xcodebuild -version
    
    - name: Authenticate with Apple Developer
      env:
        APPLE_ID: ${{ secrets.APPLE_ID }}
        APP_SPECIFIC_PASSWORD: ${{ secrets.APP_SPECIFIC_PASSWORD }}
      run: |
        echo "🔐 Testing Apple Developer authentication..."
        xcrun altool --list-providers -u "$APPLE_ID" -p "$APP_SPECIFIC_PASSWORD"
        echo "✅ Authentication successful!"
    
    - name: Create simple Xcode project
      env:
        BUNDLE_ID: ${{ github.event.inputs.bundle_id }}
      run: |
        # Create the simplest possible Xcode project
        mkdir -p SimpleApp
        cd SimpleApp
        
        # Create a basic project file
        cat > SimpleApp.xcodeproj/project.pbxproj << 'EOF'
        // !$*UTF8*$!
        {
            archiveVersion = 1;
            classes = {
            };
            objectVersion = 46;
            objects = {
                1DFB2345246A272400B07214 = {
                    isa = PBXProject;
                    attributes = {
                        LastSwiftUpdateCheck = 1140;
                        LastUpgradeCheck = 1140;
                        TargetAttributes = {
                            1DFB234C246A272400B07214 = {
                                CreatedOnToolsVersion = 11.4;
                            };
                        };
                    };
                    buildConfigurationList = 1DFB2348246A272400B07214 = {
                        isa = XCConfigurationList;
                        buildConfigurations = (
                            1DFB234D246A272400B07214 = {
                                isa = XCBuildConfiguration;
                                buildSettings = {
                                    CODE_SIGN_STYLE = Automatic;
                                    CURRENT_PROJECT_VERSION = 1;
                                    DEVELOPMENT_TEAM = "";
                                    INFOPLIST_FILE = Info.plist;
                                    IPHONEOS_DEPLOYMENT_TARGET = 14.0;
                                    PRODUCT_BUNDLE_IDENTIFIER = "$BUNDLE_ID";
                                    PRODUCT_NAME = "$(TARGET_NAME)";
                                    TARGETED_DEVICE_FAMILY = 1;
                                    VERSIONING_SYSTEM = "apple-generic";
                                };
                                name = Debug;
                            },
                        );
                        defaultConfigurationIsVisible = 0;
                        defaultConfigurationName = Release;
                    };
                    compatibilityVersion = "Xcode 3.2";
                    developmentRegion = en;
                    hasScannedForEncodings = 0;
                    knownRegions = (
                        en,
                        Base,
                    );
                    mainGroup = 1DFB2343246A272400B07214;
                    productRefGroup = 1DFB234E246A272400B07214 = {
                        isa = PBXGroup;
                        children = (
                        );
                        name = Products;
                        sourceTree = "<group>";
                    };
                    projectDirPath = "";
                    projectRoot = "";
                    targets = (
                        1DFB234C246A272400B07214 = {
                            isa = PBXNativeTarget;
                            buildConfigurationList = 1DFB234F246A272400B07214 = {
                                isa = XCConfigurationList;
                                buildConfigurations = (
                                    1DFB2350246A272400B07214 = {
                                        isa = XCBuildConfiguration;
                                        buildSettings = {
                                            CODE_SIGN_STYLE = Automatic;
                                            CURRENT_PROJECT_VERSION = 1;
                                            DEVELOPMENT_TEAM = "";
                                            INFOPLIST_FILE = Info.plist;
                                            IPHONEOS_DEPLOYMENT_TARGET = 14.0;
                                            PRODUCT_BUNDLE_IDENTIFIER = "$BUNDLE_ID";
                                            PRODUCT_NAME = "$(TARGET_NAME)";
                                            TARGETED_DEVICE_FAMILY = 1;
                                            VERSIONING_SYSTEM = "apple-generic";
                                        };
                                        name = Debug;
                                    },
                                );
                                defaultConfigurationIsVisible = 0;
                                defaultConfigurationName = Release;
                            };
                            buildPhases = (
                                1DFB2349246A272400B07214 = {
                                    isa = PBXSourcesBuildPhase;
                                    buildActionMask = 2147483647;
                                    files = (
                                    );
                                    runOnlyForDeploymentPostprocessing = 0;
                                },
                            );
                            buildRules = (
                            );
                            dependencies = (
                            );
                            name = SimpleApp;
                            productName = SimpleApp;
                            productReference = 1DFB234D246A272400B07214 = {
                                isa = PBXFileReference;
                                explicitFileType = wrapper.application;
                                includeInIndex = 0;
                                path = SimpleApp.app;
                                sourceTree = BUILT_PRODUCTS_DIR;
                            };
                            productType = "com.apple.product-type.application";
                        },
                    );
                };
            };
            rootObject = 1DFB2345246A272400B07214 = {
                isa = PBXProject;
            };
        }
        EOF
        
        # Create Info.plist
        cat > Info.plist << 'EOF'
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>CFBundleDevelopmentRegion</key>
            <string>$(DEVELOPMENT_LANGUAGE)</string>
            <key>CFBundleExecutable</key>
            <string>$(EXECUTABLE_NAME)</string>
            <key>CFBundleIdentifier</key>
            <string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
            <key>CFBundleInfoDictionaryVersion</key>
            <string>6.0</string>
            <key>CFBundleName</key>
            <string>$(PRODUCT_NAME)</string>
            <key>CFBundlePackageType</key>
            <string>APPL</string>
            <key>CFBundleShortVersionString</key>
            <string>1.0</string>
            <key>CFBundleVersion</key>
            <string>1</string>
            <key>LSRequiresIPhoneOS</key>
            <true/>
            <key>UIRequiredDeviceCapabilities</key>
            <array>
                <string>armv7</string>
            </array>
            <key>UISupportedInterfaceOrientations</key>
            <array>
                <string>UIInterfaceOrientationPortrait</string>
                <string>UIInterfaceOrientationLandscapeLeft</string>
                <string>UIInterfaceOrientationLandscapeRight</string>
            </array>
        </dict>
        </plist>
        EOF
        
        echo "✅ Created Xcode project for bundle ID: $BUNDLE_ID"
    
    - name: Generate certificates and profiles
      env:
        APPLE_ID: ${{ secrets.APPLE_ID }}
        APP_SPECIFIC_PASSWORD: ${{ secrets.APP_SPECIFIC_PASSWORD }}
      run: |
        cd SimpleApp
        
        echo "🚀 Generating certificates and provisioning profiles..."
        
        # This will trigger certificate and profile creation
        xcodebuild -project SimpleApp.xcodeproj \
          -scheme SimpleApp \
          -destination 'generic/platform=iOS' \
          -allowProvisioningUpdates \
          -allowProvisioningDeviceRegistration \
          -quiet 2>/dev/null || echo "✅ Certificate and profile generation completed"
    
    - name: Extract provisioning profiles
      run: |
        echo "📱 Searching for generated provisioning profiles..."
        
        if [ -d "$HOME/Library/MobileDevice/Provisioning Profiles" ]; then
          echo "=== Found Provisioning Profiles ==="
          ls -la "$HOME/Library/MobileDevice/Provisioning Profiles/"*.mobileprovision 2>/dev/null | head -10
          
          # Copy all provisioning profiles
          mkdir -p extracted_profiles
          cp "$HOME/Library/MobileDevice/Provisioning Profiles/"*.mobileprovision extracted_profiles/ 2>/dev/null || echo "No profiles to copy"
          
          echo "✅ Copied provisioning profiles to extracted_profiles/"
        else
          echo "❌ No provisioning profiles directory found"
          mkdir -p extracted_profiles
        fi
    
    - name: Create certificate extraction guide
      run: |
        cat > HOW_TO_EXTRACT_CERTIFICATES.md << 'EOF'
        # How to Extract Apple Developer Certificates
        
        ## The certificates have been generated on Apple's servers
        ## but need to be manually exported from a Mac.
        
        ### Steps to get your .p12 certificate:
        
        1. **Open Keychain Access** on any macOS machine
        2. **Search for "Apple Development"** in the login keychain
        3. **Find your certificate** - it should be associated with your Apple ID
        4. **Right-click the certificate** and select "Export..."
        5. **Choose .p12 format** and set a password
        6. **Save the file** - this is your developer_certificate.p12
        
        ### Provisioning Profiles:
        - The provisioning profiles are included in the artifacts
        - These are the actual .mobileprovision files generated by Apple
        - You can use them directly for code signing
        
        ### Your generated files:
        - Bundle ID: ${{ github.event.inputs.bundle_id }}
        - Apple ID: ${{ secrets.APPLE_ID }}
        - App-Specific Password: [stored in GitHub secrets]
        
        ### Next steps:
        1. Download the artifacts from this workflow
        2. Manually export the certificate from Keychain Access as described above
        3. Use both the .p12 and .mobileprovision files for code signing
        EOF
        
        echo "P12 Export Password: [set this when manually exporting]" > passwords.txt
        echo "Bundle ID: ${{ github.event.inputs.bundle_id }}" >> passwords.txt
        echo "Apple ID: ${{ secrets.APPLE_ID }}" >> passwords.txt
    
    - name: Package artifacts
      run: |
        # Create placeholder .p12 (you'll replace this with the real one)
        echo "This is a placeholder. Export the real certificate from Keychain Access." > developer_certificate_placeholder.p12
        
        # Package everything
        zip -r apple_credentials.zip \
          extracted_profiles/ \
          HOW_TO_EXTRACT_CERTIFICATES.md \
          passwords.txt \
          developer_certificate_placeholder.p12
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: apple-developer-credentials
        path: |
          apple_credentials.zip
          extracted_profiles/
          HOW_TO_EXTRACT_CERTIFICATES.md
          passwords.txt
          developer_certificate_placeholder.p12
