name: Sign iOS IPA (Free Apple Developer)

on:
  workflow_dispatch:
    inputs:
      ipa_url:
        description: "Direct download URL for the IPA to sign"
        required: true

jobs:
  sign:
    runs-on: macos-latest
    env:
      FASTLANE_USER: ${{ secrets.APPLE_ID }}
      FASTLANE_PASSWORD: ${{ secrets.APP_SPECIFIC_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Fastlane
        run: |
          brew install fastlane
          echo "✅ Fastlane installed"

      - name: Download IPA
        run: |
          echo "📦 Downloading IPA..."
          curl -L -o app.ipa "${{ github.event.inputs.ipa_url }}"
          ls -lh app.ipa

      - name: Extract IPA
        run: |
          mkdir extracted
          unzip app.ipa -d extracted
          echo "✅ IPA extracted"

      - name: Prepare signing environment
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles

      - name: Sign IPA using Fastlane (Free Apple Account)
        run: |
          cd extracted
          echo "🔧 Signing IPA..."
          unset FASTLANE_SESSION
          fastlane sigh --username "$FASTLANE_USER" --adhoc true --skip_certificate_verification --force

          # Copy the first downloaded provisioning profile
          PROFILE=$(ls *.mobileprovision | head -n 1)
          cp "$PROFILE" ~/Library/MobileDevice/Provisioning\ Profiles/

          # Find the .app inside Payload
          APP_PATH=$(find Payload -name "*.app" | head -n 1)
          echo "Signing app at $APP_PATH..."
          codesign -f -s "Apple Development" --entitlements entitlements.plist "$APP_PATH"

      - name: Repackage Signed IPA
        run: |
          cd extracted
          zip -r ../signed-app.ipa Payload/
          cd ..
          echo "✅ Signed IPA repackaged"

      - name: Upload Signed IPA
        uses: actions/upload-artifact@v4
        with:
          name: signed-ipa
          path: signed-app.ipa
