name: Sign iOS IPA

on:
  workflow_dispatch:
    inputs:
      ipa_path:
        description: "Path to the unsigned IPA file"
        required: true
        default: "MyApp.ipa"

jobs:
  sign:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install required tools
        run: |
          xcode-select --install || true
          echo "✅ Xcode command line tools available"

      - name: Setup Apple ID
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_PASS: ${{ secrets.APPLE_PASS }}
        run: |
          echo "Logging into Xcode..."
          xcrun altool --authenticate-app -u "$APPLE_ID" -p "$APPLE_PASS" || echo "Will sign manually"

      - name: Extract IPA
        run: |
          mkdir extracted
          cd extracted
          unzip ../${{ github.event.inputs.ipa_path }}

      - name: Find signing identity
        run: |
          security find-identity -v -p codesigning || echo "No signing identity found yet"

      - name: Sign the app
        env:
          APPLE_IDENTITY: ${{ secrets.APPLE_IDENTITY }}
        run: |
          cd extracted
          echo "Signing using identity: $APPLE_IDENTITY"
          codesign --force --sign "$APPLE_IDENTITY" Payload/*.app
          cd ..

      - name: Repackage IPA
        run: |
          cd extracted
          zip -r ../signed-app.ipa Payload/
          cd ..

      - name: Upload signed IPA
        uses: actions/upload-artifact@v4
        with:
          name: signed-ipa
          path: signed-app.ipa
