name: Sign iOS IPA (Real Device Ready)

on:
  workflow_dispatch:
    inputs:
      ipa_url:
        description: "Direct download URL for the IPA to sign"
        required: true

jobs:
  sign:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew install fastlane
          echo "✅ Fastlane installed"

      - name: Download IPA
        run: |
          echo "📦 Downloading IPA..."
          curl -L -o app.ipa "${{ github.event.inputs.ipa_url }}"
          ls -lh app.ipa

      - name: Extract IPA
        run: |
          mkdir extracted
          cd extracted
          unzip ../app.ipa
          echo "✅ IPA extracted"

      - name: Setup Fastlane authentication
        env:
          FASTLANE_USER: ${{ secrets.APPLE_ID }}
          FASTLANE_PASSWORD: ${{ secrets.APPLE_PASS }}
        run: |
          echo "🔐 Authenticating with Apple..."
          # This validates credentials and ensures they work non-interactively
          fastlane spaceauth -u "$FASTLANE_USER" || echo "Auth session handled"

      - name: Generate provisioning profile and sign
        env:
          FASTLANE_USER: ${{ secrets.APPLE_ID }}
          FASTLANE_PASSWORD: ${{ secrets.APPLE_PASS }}
        run: |
          cd extracted
          echo "🔧 Requesting provisioning profile from Apple..."
          fastlane sigh --username "$FASTLANE_USER" --adhoc true --skip_certificate_verification
          echo "✅ Provisioning profile downloaded"

          PROFILE=$(ls *.mobileprovision | head -n 1)
          echo "Using profile: $PROFILE"

          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp "$PROFILE" ~/Library/MobileDevice/Provisioning\ Profiles/

          APP_PATH=$(find Payload -name "*.app" | head -n 1)
          echo "Signing $APP_PATH..."
          codesign -f -s "Apple Development" --entitlements entitlements.plist "$APP_PATH"

      - name: Repackage Signed IPA
        run: |
          cd extracted
          zip -r ../signed-app.ipa Payload/
          cd ..
          echo "📦 Signed IPA repackaged successfully"

      - name: Upload Signed IPA
        uses: actions/upload-artifact@v4
        with:
          name: signed-ipa
          path: signed-app.ipa
