name: Sign iOS IPA (Free Apple Developer)

on:
  workflow_dispatch:
    inputs:
      ipa_url:
        description: "Direct download URL for the IPA to sign"
        required: true

jobs:
  sign:
    runs-on: macos-latest

    env:
      FASTLANE_USER: ${{ secrets.APPLE_ID }}
      FASTLANE_PASSWORD: ${{ secrets.APPLE_PASS }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew install fastlane
          echo "✅ Fastlane installed"

      - name: Download IPA
        run: |
          echo "📦 Downloading IPA..."
          curl -L -o app.ipa "${{ github.event.inputs.ipa_url }}"
          ls -lh app.ipa

      - name: Extract IPA
        run: |
          mkdir extracted
          cd extracted
          unzip ../app.ipa
          echo "✅ IPA extracted"

      - name: Prepare signing
        run: |
          cd extracted
          unset FASTLANE_SESSION
          echo "🔧 Preparing provisioning profile for free Apple account..."
          # Force sigh to regenerate profile for free account
          fastlane sigh --username "$FASTLANE_USER" --adhoc true --skip_certificate_verification --force

          # Copy provisioning profile to standard location
          PROFILE=$(ls *.mobileprovision | head -n 1)
          echo "Using provisioning profile: $PROFILE"
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp "$PROFILE" ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Sign IPA
        run: |
          cd extracted
          APP_PATH=$(find Payload -name "*.app" | head -n 1)
          echo "Signing app at $APP_PATH..."
          # Auto-generate entitlements from Info.plist
          /usr/libexec/PlistBuddy -c "Print :CFBundleIdentifier" "$APP_PATH/Info.plist"
          # Signing with Apple Development certificate
          codesign -f -s "Apple Development" --entitlements entitlements.plist "$APP_PATH"
          echo "✅ App signed successfully"

      - name: Repackage Signed IPA
        run: |
          cd extracted
          zip -r ../signed-app.ipa Payload/
          cd ..
          echo "📦 Signed IPA repackaged successfully"

      - name: Upload Signed IPA
        uses: actions/upload-artifact@v4
        with:
          name: signed-ipa
          path: signed-app.ipa
