name: Sign IPA with Apple ID

on:
  workflow_dispatch:
    inputs:
      sideloader_url:
        description: "Enter the direct download URL of the sideloader-cli binary"
        required: true
        type: string
        default: "https://github.com/Dadoum/Sideloader/releases/latest/download/sideloader-cli-x86_64-linux-gnu"
      ipa_url:
        description: "Enter the direct download URL of the unsigned IPA"
        required: true
        type: string

jobs:
  sign_ipa:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Sideloader CLI
        run: |
          mkdir -p tools
          cd tools
          wget "${{ github.event.inputs.sideloader_url }}" -O sideloader-cli
          chmod +x sideloader-cli
          echo "✅ Downloaded Sideloader from ${{ github.event.inputs.sideloader_url }}"

      - name: Download unsigned IPA
        run: |
          mkdir -p ipa
          wget "${{ github.event.inputs.ipa_url }}" -O ipa/unsigned.ipa
          echo "✅ Downloaded IPA from ${{ github.event.inputs.ipa_url }}"

      - name: Sign IPA using Apple ID + App-Specific Password
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APP_SPECIFIC_PASSWORD: ${{ secrets.APP_SPECIFIC_PASSWORD }}
        run: |
          cd tools
          ./sideloader-cli sign ../ipa/unsigned.ipa \
            --apple-id "$APPLE_ID" \
            --apple-password "$APP_SPECIFIC_PASSWORD" \
            --output ../ipa/signed.ipa \
            --debug

      - name: Upload signed IPA as artifact
        uses: actions/upload-artifact@v4
        with:
          name: signed-ipa
          path: ipa/signed.ipa
